### ISSUE TITLE
Move everything to src folder and except packages.json

### ISSUE THREAD

**Issue by grvsooryen** [thepassle/reddit-pwa#2]
keeping index.html at root level make resource differentiation difficult. Can all the web related content be placed inside `src` folder including `web_modules` folder while packages.json at top level? Also a build strategy would be great to place inside `dist` or `build` folder.

**Comment by thepassle** [comment]
I think this is somewhat of a preference thing. I prefer to have my index at the root level. But you could place everything in a `src` folder, sure. Also, the point is to not have a build strategy, so I'm not exactly sure what you mean by that.

You could add a build step somewhere down the line if you start running into problems, or start doing performance optimizations. But this project is a showcase on how to develop _without_ a build step, so its unlikely i'll add a dist or build folder.

**Comment by grvsooryen** [comment]
Is it possible to auto-generate imports like `es-dev-server` does with `--node-resolve`?
```html
 <script type="importmap-shim">
      {
        "imports": {
          "@vaadin/router": "/web_modules/@vaadin/router.js",
          "lit-element": "/web_modules/lit-element.js",
          "std:kv-storage": [
            "std:kv-storage",
            "/web_modules/kv-storage-polyfill.js"
          ]
        }
      }
    </script>
```
OR Can we rewrite web_modules onto another location if possible?

**Comment by thepassle** [comment]
Not sure what you mean by that. `es-dev-server` does not generate import maps, no. Pika, however, will output an import map in the `web_modules` folder.

If you want `es-dev-server` to resolve from the `web_modules` folder, you can use `es-dev-server --modules-dir web_modules`

**Comment by grvsooryen** [comment]
ok this is what I was looking for. I shall give that a try. Thanks
